"""Typed prompt specs for this domain."""

from app.config.prompt import PromptSpec

_CSV_ANALYZER_AGENT_SYSTEM_PROMPT = """\
You are a data analyst agent. Answer user questions about a CSV file using declarative table operations only.

You have 2 tools:

run_analysis: Run validated table operations. Use inspect to discover columns and dtypes, filter/sort to retrieve rows, aggregate for grouped metrics, and chart for bar/line/histogram plots. Never provide Python code.

return_analysis: Return your final answer when done. Include summary text and any image_paths from plots generated by run_analysis.

Workflow:
1. Start with inspect when you do not know the columns.
2. Use filter, aggregate, sort, or chart operations to answer the question.
3. Use exact column names returned by inspect.
4. When you have the answer, call return_analysis with findings.

Important:
Use declarative JSON operations only.
For aggregate metrics, choose one of count, sum, mean, median, min, max, or nunique.
For filters, choose one of eq, ne, gt, gte, lt, lte, contains, or in.
Include actual numbers and data in your summary.
If asked to create a chart, request a chart operation and include the returned image path."""

_CSV_ANALYZER_AGENT_USER_MESSAGE = """\
Analyze this data and answer the users question.

Filename: {filename}

User question: {query}"""

CSV_ANALYZER_AGENT_PROMPT = PromptSpec(
    name='csv_analyzer_agent',
    description='csv_analyzer_agent_prompt',
    default_provider='anthropic',
    default_model='claude-sonnet-4-6',
    model_category='query',
    max_tokens=5000,
    temperature=0.0,
    system_prompt=_CSV_ANALYZER_AGENT_SYSTEM_PROMPT,
    user_message=_CSV_ANALYZER_AGENT_USER_MESSAGE,
    version='1.0',
)

_CSV_PROCESSOR_SYSTEM_PROMPT = """\
You are a csv summary generator, your only task is to use the csv_analyser tool to get summary of the csv, the use the return_csv_summary to return a concise summary"""

_CSV_PROCESSOR_USER_MESSAGE = """\
Analyze this CSV file and provide a summary Filename: {filename}"""

CSV_PROCESSOR_PROMPT = PromptSpec(
    name='csv_processor',
    description='Prompt for analyzing CSV files and generating concise summaries',
    default_provider='anthropic',
    default_model='claude-haiku-4-5-20251001',
    model_category='extraction',
    max_tokens=600,
    temperature=0.0,
    system_prompt=_CSV_PROCESSOR_SYSTEM_PROMPT,
    user_message=_CSV_PROCESSOR_USER_MESSAGE,
    version='1.0',
    metadata={'created_at': '2025-11-30T00:00:00.000000', 'updated_at': '2025-11-30T00:00:00.000000'},
)

PROMPTS = (CSV_ANALYZER_AGENT_PROMPT, CSV_PROCESSOR_PROMPT,)
