"""Typed provider-neutral model/tool runtime."""

from app.agents.runtime.contract import (
    MediaPart,
    ProviderAdapter,
    ProviderErrorInfo,
    ProviderErrorKind,
    ProviderMetadataPart,
    ProviderState,
    RunEvent,
    RunLimits,
    RunMessage,
    RunRequest,
    RunResult,
    StructuredResult,
    TextPart,
    ToolChoice,
    ToolCall,
    ToolCallPart,
    ToolResult,
    ToolResultPart,
    Usage,
)
from app.agents.runtime.provider import (
    compile_agent_tools_for_provider,
    compile_tools_for_provider,
    get_provider_adapter,
    run_with_provider,
    stream_with_provider,
)
from app.agents.runtime.error import ProviderRunError, ToolResultError
from app.agents.runtime.run import RuntimeRunner
from app.agents.runtime.result import (
    require_tool_result_payload,
    successful_tool_results,
    tool_result_payloads,
)
from app.agents.runtime.tool import (
    LocalToolSpec,
    McpCallInput,
    McpProxyToolSpec,
    ProviderToolSpec,
    ToolContext,
    ToolOutput,
    ToolSpec,
)
from app.agents.runtime.binding import bind_local_tools, echo_input

__all__ = [
    "MediaPart",
    "ProviderAdapter",
    "ProviderErrorInfo",
    "ProviderErrorKind",
    "ProviderMetadataPart",
    "ProviderState",
    "ProviderRunError",
    "ToolResultError",
    "RunEvent",
    "RunLimits",
    "RunMessage",
    "RunRequest",
    "RunResult",
    "RuntimeRunner",
    "require_tool_result_payload",
    "successful_tool_results",
    "tool_result_payloads",
    "StructuredResult",
    "TextPart",
    "ToolChoice",
    "ToolCall",
    "ToolCallPart",
    "ToolContext",
    "ToolOutput",
    "ToolResult",
    "ToolResultPart",
    "LocalToolSpec",
    "McpCallInput",
    "McpProxyToolSpec",
    "ProviderToolSpec",
    "ToolSpec",
    "Usage",
    "bind_local_tools",
    "compile_agent_tools_for_provider",
    "compile_tools_for_provider",
    "get_provider_adapter",
    "run_with_provider",
    "stream_with_provider",
    "echo_input",
]
