"""Typed tool contracts for model-visible tools."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, Optional, Type, TypeAlias

from pydantic import BaseModel, ConfigDict, Field

from app.base.contracts import ContractModel


class ToolContext(ContractModel):
    """Runtime values passed to local tool handlers."""

    project_id: Optional[str] = None
    user_id: Optional[str] = None
    workspace_id: Optional[str] = None
    chat_id: Optional[str] = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class EmptyInput(ContractModel):
    """Default empty input contract for tools with no model arguments."""


class ToolOutput(ContractModel):
    """Explicit result envelope returned by local tool handlers."""

    content: Any
    is_error: bool = False


ToolHandler = Callable[[BaseModel, ToolContext], Any]


class BaseToolSpec(BaseModel):
    """Shared data for model-visible tool specs."""

    model_config = ConfigDict(arbitrary_types_allowed=True, extra="forbid")

    name: str
    description: str
    metadata: dict[str, Any] = Field(default_factory=dict)


class LocalToolSpec(BaseToolSpec):
    """Pydantic-owned app-local tool contract.

    `input_model` is the contract the model must satisfy before a local handler
    runs. Provider JSON schemas are generated by provider adapters only; JSON
    is not a runtime-local source of truth.
    """

    kind: Literal["local"] = "local"
    input_model: Type[BaseModel] = Field(default=EmptyInput, exclude=True)
    output_model: Optional[Type[BaseModel]] = Field(default=None, exclude=True)
    handler: Optional[ToolHandler] = Field(default=None, exclude=True)
    terminates_run: bool = False
    terminates_when: Optional[str] = None

    def validate_input(self, value: Any) -> BaseModel:
        """Validate raw model-provided input before handler execution."""
        return _validate_input(self, value)

    def execute(self, value: Any, context: ToolContext) -> Any:
        """Validate input and execute a local handler."""
        return _execute_tool(self, value, context)

    def execute_validated(self, value: BaseModel, context: ToolContext) -> Any:
        """Execute a local handler with already validated input."""
        return _execute_tool(self, value, context)


class ProviderToolSpec(BaseToolSpec):
    """Provider-hosted tool contract.

    These tools are executed by the selected model provider. The runtime must
    not route provider-hosted tool calls through local handlers.
    """

    kind: Literal["provider"] = "provider"
    provider_type: str


class McpCallInput(ContractModel):
    """Single app-owned proxy input for all enabled MCP tools."""

    tool_id: str
    arguments_json: str = Field(
        default="{}",
        description=(
            "JSON object string containing the original MCP tool arguments. "
            "Use {} when the tool takes no arguments."
        ),
    )


class McpProxyToolSpec(BaseToolSpec):
    """App-owned MCP proxy tool exposed to providers as one local function."""

    kind: Literal["mcp_proxy"] = "mcp_proxy"
    input_model: Type[BaseModel] = Field(default=McpCallInput, exclude=True)
    output_model: Optional[Type[BaseModel]] = Field(default=None, exclude=True)
    handler: Optional[ToolHandler] = Field(default=None, exclude=True)
    terminates_run: bool = False
    terminates_when: Optional[str] = None

    def validate_input(self, value: Any) -> BaseModel:
        """Validate raw model-provided input before handler execution."""
        return _validate_input(self, value)

    def execute(self, value: Any, context: ToolContext) -> Any:
        """Validate input and execute the MCP proxy handler."""
        return _execute_tool(self, value, context)

    def execute_validated(self, value: BaseModel, context: ToolContext) -> Any:
        """Execute the MCP proxy handler with already validated input."""
        return _execute_tool(self, value, context)


ToolSpec: TypeAlias = LocalToolSpec | ProviderToolSpec | McpProxyToolSpec


def validate_tool_spec(value: Any) -> ToolSpec:
    """Return a concrete tool spec instance from registry data."""
    if isinstance(value, (LocalToolSpec, ProviderToolSpec, McpProxyToolSpec)):
        return value
    if not isinstance(value, dict):
        raise TypeError(f"Unsupported tool spec type: {type(value).__name__}")

    kind = value.get("kind", "local")
    if kind == "local":
        return LocalToolSpec.model_validate(value)
    if kind == "provider":
        return ProviderToolSpec.model_validate(value)
    if kind == "mcp_proxy":
        return McpProxyToolSpec.model_validate(value)
    raise ValueError(f"Unsupported tool spec kind: {kind!r}")


def _validate_input(spec: LocalToolSpec | McpProxyToolSpec, value: Any) -> BaseModel:
    input_value = {} if value is None else value
    return spec.input_model.model_validate(input_value)


def _execute_tool(
    spec: LocalToolSpec | McpProxyToolSpec,
    value: Any,
    context: ToolContext,
) -> Any:
    if spec.handler is None:
        raise ValueError(f"Local tool {spec.name!r} has no handler")

    parsed_input = value if isinstance(value, BaseModel) else spec.validate_input(value)
    result = spec.handler(parsed_input, context)

    if isinstance(result, ToolOutput):
        return result

    if spec.output_model is None:
        if isinstance(result, BaseModel):
            return result.model_dump(mode="json")
        return result

    parsed_output = spec.output_model.model_validate(result)
    return parsed_output.model_dump(mode="json")


def provider_tool(
    *,
    registry_name: str,
    name: str,
    provider_type: str,
    metadata: Optional[dict[str, Any]] = None,
) -> ToolSpec:
    """Build a provider-hosted tool spec."""
    merged_metadata = dict(metadata or {})
    merged_metadata["registry_name"] = registry_name
    return ProviderToolSpec(
        name=name,
        description=f"Provider-hosted tool: {name}",
        provider_type=provider_type,
        metadata=merged_metadata,
    )
